apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-servianld
  namespace: ingress-controller
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: srram125@gmail.com
    privateKeySecretRef:
      name: letsencrypt-servianld
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret-cert
  namespace: ingress-controller
spec:
  secretName: tls-secret
  dnsNames:
  - servianldcluster.australiaeast.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-servianld
    kind: ClusterIssuer
