apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-istioaks
  namespace: ingress-controller
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: srram125@gmail.com
    privateKeySecretRef:
      name: letsencrypt-istioaks
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: ingress-controller
spec:
  secretName: tls-secret
  dnsNames:
  - istioaks.centralindia.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-istioaks
    kind: ClusterIssuer
